// Generated by tools/embed_html.py from web/index.html - do not edit.
#pragma once
#include <pgmspace.h>

static const char INDEX_HTML[] PROGMEM = R"rawliteral(<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta name="theme-color" content="#d9eeff">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="default">
<title>RelayTimer</title>
<style>
:root{
  --bg1:#eaf6ff; --bg2:#cfe8ff; --ink:#0d2a47; --ink2:#4a6a8a; --ink3:#8aa5c0;
  --pri:#2f8cff; --pri2:#5fc3ff; --pri-soft:#e1f0ff; --glass:rgba(255,255,255,.72);
  --line:rgba(47,140,255,.14); --ok:#16c79a; --warn:#ff9f43; --bad:#ff5d73;
  --r:22px; --shadow:0 10px 30px -12px rgba(30,100,190,.35), 0 2px 6px -2px rgba(30,100,190,.12);
  --grad:linear-gradient(135deg,#5fc3ff 0%,#2f8cff 55%,#3d6dff 100%);
}
*{box-sizing:border-box;-webkit-tap-highlight-color:transparent}
[hidden]{display:none!important}
html,body{margin:0;height:100%}
body{
  font:15px/1.4 -apple-system,BlinkMacSystemFont,"SF Pro Text","Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif;
  color:var(--ink); background:var(--bg1);
  background-image:
    radial-gradient(900px 500px at -10% -10%,#bfe3ff 0%,transparent 60%),
    radial-gradient(700px 500px at 110% 10%,#d7ecff 0%,transparent 55%),
    radial-gradient(800px 600px at 50% 120%,#c4e2ff 0%,transparent 60%);
  background-attachment:fixed; min-height:100%;
}
button,input,select{font:inherit;color:inherit}
button{cursor:pointer;border:0;background:none}
.app{max-width:560px;margin:0 auto;padding:calc(env(safe-area-inset-top) + 14px) 16px calc(env(safe-area-inset-bottom) + 110px);transition:padding .3s}
body.dirty .app{padding-bottom:calc(env(safe-area-inset-bottom) + 175px)}

/* header */
.top{display:flex;align-items:center;justify-content:space-between;gap:12px;margin:4px 2px 18px}
.brand{display:flex;align-items:center;gap:10px}
.logo{width:40px;height:40px;border-radius:13px;background:var(--grad);display:grid;place-items:center;box-shadow:0 8px 18px -6px rgba(47,140,255,.7)}
.logo svg{width:22px;height:22px;color:#fff}
.brand h1{font-size:20px;margin:0;letter-spacing:-.3px}
.brand small{display:block;color:var(--ink2);font-size:12px;margin-top:1px}
.clock{background:var(--glass);backdrop-filter:blur(14px);-webkit-backdrop-filter:blur(14px);border:1px solid rgba(255,255,255,.8);
  border-radius:16px;padding:7px 12px;text-align:right;box-shadow:var(--shadow);min-width:96px}
.clock b{display:block;font-size:17px;font-variant-numeric:tabular-nums;letter-spacing:-.2px}
.clock span{font-size:11px;color:var(--ink2);display:flex;align-items:center;gap:5px;justify-content:flex-end}
.dot{width:7px;height:7px;border-radius:50%;background:var(--ok);box-shadow:0 0 0 3px rgba(22,199,154,.18)}
.dot.off{background:var(--bad);box-shadow:0 0 0 3px rgba(255,93,115,.18)}

/* generic */
.card{background:var(--glass);backdrop-filter:blur(18px);-webkit-backdrop-filter:blur(18px);border:1px solid rgba(255,255,255,.85);
  border-radius:var(--r);box-shadow:var(--shadow);padding:16px;margin-bottom:14px}
.h2{font-size:13px;font-weight:700;text-transform:uppercase;letter-spacing:.8px;color:var(--ink2);margin:22px 4px 10px}
.row{display:flex;align-items:center;gap:10px}
.grow{flex:1;min-width:0}
.muted{color:var(--ink2)}
.tiny{font-size:12px;color:var(--ink3)}
.view{display:none;animation:in .28s ease}
.view.on{display:block}
@keyframes in{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:none}}

.banner{display:flex;align-items:center;gap:12px;background:linear-gradient(135deg,#fff4e6,#ffe9d1);border:1px solid #ffd9ad;
  border-radius:18px;padding:12px 14px;margin-bottom:14px;color:#7a4a12}
.banner svg{flex:none;width:22px;height:22px}
.banner .grow b{display:block}

.btn{display:inline-flex;align-items:center;justify-content:center;gap:8px;height:44px;padding:0 18px;border-radius:14px;font-weight:600;
  background:var(--grad);color:#fff;box-shadow:0 8px 18px -8px rgba(47,140,255,.8);transition:transform .12s, filter .2s}
.btn:active{transform:scale(.97)}
.btn.ghost{background:var(--pri-soft);color:var(--pri);box-shadow:none}
.btn.light{background:#fff;color:var(--ink);box-shadow:0 2px 8px -3px rgba(30,100,190,.25)}
.btn.danger{background:#ffe8ec;color:var(--bad);box-shadow:none}
.btn.sm{height:36px;padding:0 13px;border-radius:12px;font-size:14px}
.btn.block{width:100%}
.btn svg{width:18px;height:18px}
.iconbtn{width:38px;height:38px;border-radius:12px;display:grid;place-items:center;color:var(--ink2);background:rgba(255,255,255,.6)}
.iconbtn svg{width:18px;height:18px}
.iconbtn:active{transform:scale(.94)}

/* segmented control */
.seg{position:relative;display:grid;grid-auto-flow:column;grid-auto-columns:1fr;background:rgba(47,140,255,.09);border-radius:14px;padding:4px}
.seg button{position:relative;z-index:1;height:36px;border-radius:11px;font-weight:600;color:var(--ink2);font-size:14px;transition:color .2s}
.seg button.on{color:var(--ink)}
.seg .pill{position:absolute;z-index:0;top:4px;bottom:4px;left:4px;border-radius:11px;background:#fff;box-shadow:0 3px 10px -3px rgba(30,100,190,.35);
  transition:transform .3s cubic-bezier(.3,1.3,.5,1)}

/* relay card */
.relay{position:relative;overflow:hidden}
.relay .head{display:flex;align-items:center;gap:14px}
.power{width:64px;height:64px;border-radius:50%;flex:none;display:grid;place-items:center;background:#eef6ff;color:var(--ink3);
  transition:all .35s;box-shadow:inset 0 0 0 1px var(--line)}
.power svg{width:28px;height:28px}
.relay.is-on .power{background:var(--grad);color:#fff;box-shadow:0 0 0 6px rgba(95,195,255,.22),0 12px 26px -8px rgba(47,140,255,.9)}
.relay.is-on .power{animation:glow 2.6s ease-in-out infinite}
@keyframes glow{50%{box-shadow:0 0 0 11px rgba(95,195,255,.12),0 12px 26px -8px rgba(47,140,255,.9)}}
.relay h3{margin:0;font-size:18px;letter-spacing:-.2px}
.state{display:inline-flex;align-items:center;gap:6px;font-size:13px;font-weight:700;margin-top:3px;color:var(--ink3)}
.relay.is-on .state{color:var(--pri)}
.next{font-size:13px;color:var(--ink2);margin-top:2px}
.relay .seg{margin-top:14px}
.relay::after{content:"";position:absolute;right:-60px;top:-60px;width:180px;height:180px;border-radius:50%;
  background:radial-gradient(circle,rgba(95,195,255,.25),transparent 70%);opacity:0;transition:opacity .4s;pointer-events:none}
.relay.is-on::after{opacity:1}

/* timeline */
.tl{position:relative;height:30px;border-radius:10px;background:repeating-linear-gradient(90deg,rgba(47,140,255,.06) 0 calc(100%/24 - 1px),rgba(47,140,255,.13) calc(100%/24 - 1px) calc(100%/24));margin-top:14px;overflow:hidden}
.tl.slim{height:18px;margin-top:0;border-radius:7px}
.tl i{position:absolute;top:0;bottom:0;background:var(--grad);border-radius:7px;box-shadow:0 2px 8px -2px rgba(47,140,255,.7)}
.tl .now{position:absolute;top:-2px;bottom:-2px;width:2px;background:var(--ink);border-radius:2px;box-shadow:0 0 0 2px rgba(255,255,255,.7)}
.ticks{display:flex;justify-content:space-between;font-size:10px;color:var(--ink3);margin-top:5px;font-variant-numeric:tabular-nums}

/* schedule editor */
.days{display:grid;grid-template-columns:repeat(7,1fr);gap:6px;margin:14px 0 4px}
.day{position:relative;height:56px;border-radius:15px;background:rgba(255,255,255,.65);display:flex;flex-direction:column;align-items:center;justify-content:center;
  font-weight:700;font-size:13px;color:var(--ink2);border:1px solid rgba(255,255,255,.9);transition:all .2s}
.day small{font-size:10px;font-weight:600;color:var(--ink3);margin-top:2px}
.day.on{background:var(--grad);color:#fff;box-shadow:0 8px 18px -8px rgba(47,140,255,.9);border-color:transparent}
.day.on small{color:rgba(255,255,255,.85)}
.day.today::before{content:"";position:absolute;top:6px;width:5px;height:5px;border-radius:50%;background:var(--pri)}
.day.on.today::before{background:#fff}
.slot{display:flex;align-items:center;gap:8px;background:#fff;border-radius:16px;padding:10px 10px 10px 14px;margin-top:10px;
  box-shadow:0 2px 10px -4px rgba(30,100,190,.25);animation:in .25s ease}
.slot .lab{font-size:11px;font-weight:700;letter-spacing:.5px;text-transform:uppercase;color:var(--ink3)}
.slot input[type=time]{border:0;background:var(--pri-soft);border-radius:11px;padding:7px 9px;font-weight:700;font-size:16px;color:var(--ink);
  font-variant-numeric:tabular-nums;min-width:0;width:100%;-webkit-appearance:none;appearance:none;min-height:38px;padding:7px 4px;text-align:center}
.slot input[type=time]::-webkit-calendar-picker-indicator{display:none}
.slot .arrow{color:var(--ink3);flex:none}
.slot .f{flex:1;min-width:0}
.slot .dur{font-size:11px;color:var(--pri);font-weight:600;margin-top:3px}
.empty{text-align:center;padding:26px 10px 14px;color:var(--ink2)}
.empty svg{width:44px;height:44px;color:var(--pri2);opacity:.8}
.toolbar{display:flex;gap:8px;margin-top:14px;flex-wrap:wrap}
.toolbar .btn{flex:1}

/* week overview */
.wk{display:grid;grid-template-columns:38px 1fr;gap:9px 10px;align-items:center}
.wk b{font-size:12px;color:var(--ink2)}
.wk b.today{color:var(--pri)}
.wk .tl{cursor:pointer}

/* forms */
label.fld{display:block;margin-top:12px}
label.fld span{display:block;font-size:12px;font-weight:600;color:var(--ink2);margin:0 0 6px 4px}
.inp{width:100%;height:46px;border-radius:14px;border:1px solid var(--line);background:#fff;padding:0 14px;outline:none;transition:box-shadow .2s,border-color .2s;-webkit-appearance:none;appearance:none}
.inp:focus{border-color:var(--pri);box-shadow:0 0 0 4px rgba(47,140,255,.15)}
select.inp{background:#fff url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='8' fill='none' stroke='%234a6a8a' stroke-width='2'%3E%3Cpath d='M1 1l5 5 5-5'/%3E%3C/svg%3E") no-repeat right 14px center;padding-right:36px}
.kv{display:flex;justify-content:space-between;padding:9px 2px;border-bottom:1px solid var(--line);font-size:14px}
.kv:last-child{border:0}
.kv span{color:var(--ink2)}
.kv b{font-weight:600;text-align:right;word-break:break-all}

/* bottom nav */
.nav{position:fixed;left:50%;transform:translateX(-50%);bottom:calc(env(safe-area-inset-bottom) + 14px);width:calc(100% - 32px);max-width:420px;
  display:grid;grid-template-columns:repeat(4,1fr);background:rgba(255,255,255,.78);backdrop-filter:blur(20px) saturate(1.4);-webkit-backdrop-filter:blur(20px) saturate(1.4);
  border:1px solid rgba(255,255,255,.95);border-radius:24px;padding:7px;box-shadow:0 18px 40px -14px rgba(30,100,190,.45);z-index:20}
.nav button{display:flex;flex-direction:column;align-items:center;gap:3px;padding:7px 0;border-radius:17px;color:var(--ink3);font-size:11px;font-weight:600;transition:all .25s}
.nav button svg{width:22px;height:22px}
.nav button.on{color:var(--pri);background:var(--pri-soft)}

/* save bar */
.savebar{position:fixed;left:50%;bottom:calc(env(safe-area-inset-bottom) + 96px);transform:translate(-50%,160%);width:calc(100% - 32px);max-width:420px;
  display:flex;align-items:center;gap:10px;background:var(--ink);color:#fff;border-radius:18px;padding:9px 9px 9px 16px;z-index:19;
  box-shadow:0 16px 36px -12px rgba(13,42,71,.6);transition:transform .35s cubic-bezier(.3,1.3,.5,1);font-size:14px}
.savebar.show{transform:translate(-50%,0)}
.savebar .btn.light{background:rgba(255,255,255,.14);color:#fff}

/* sheet */
.scrim{position:fixed;inset:0;background:rgba(13,42,71,.32);backdrop-filter:blur(3px);-webkit-backdrop-filter:blur(3px);opacity:0;pointer-events:none;transition:opacity .25s;z-index:40}
.scrim.show{opacity:1;pointer-events:auto}
.sheet{position:fixed;left:0;right:0;bottom:0;margin:0 auto;max-width:560px;background:#f6fbff;border-radius:28px 28px 0 0;padding:10px 18px calc(env(safe-area-inset-bottom) + 20px);
  transform:translateY(105%);transition:transform .35s cubic-bezier(.2,1,.3,1);z-index:41;max-height:86vh;overflow:auto;box-shadow:0 -20px 50px -20px rgba(13,42,71,.4)}
.sheet.show{transform:none}
.grab{width:42px;height:5px;border-radius:5px;background:#c9dcef;margin:0 auto 12px}
.sheet h3{margin:4px 0 4px;font-size:19px}
.chk{display:flex;align-items:center;gap:12px;padding:12px 14px;background:#fff;border-radius:14px;margin-top:8px;box-shadow:0 1px 6px -3px rgba(30,100,190,.25)}
.chk input{display:none}
.chk .box{width:24px;height:24px;border-radius:8px;border:2px solid #c7dbf0;display:grid;place-items:center;transition:all .2s;flex:none}
.chk .box svg{width:14px;height:14px;color:#fff;opacity:0;transition:opacity .15s}
.chk input:checked + .box{background:var(--grad);border-color:transparent}
.chk input:checked + .box svg{opacity:1}
.chk input:disabled ~ *{opacity:.45}
.net{display:flex;align-items:center;gap:12px;padding:12px 14px;background:#fff;border-radius:14px;margin-top:8px;width:100%;text-align:left;box-shadow:0 1px 6px -3px rgba(30,100,190,.25)}
.bars{display:flex;align-items:flex-end;gap:2px;height:16px}
.bars i{width:4px;border-radius:2px;background:#cfe1f3}
.bars i.f{background:var(--pri)}

/* toast */
.toast{position:fixed;top:calc(env(safe-area-inset-top) + 14px);left:50%;transform:translate(-50%,-160%);background:#fff;color:var(--ink);padding:11px 16px;border-radius:16px;
  box-shadow:0 14px 30px -10px rgba(30,100,190,.5);font-weight:600;font-size:14px;z-index:60;display:flex;align-items:center;gap:9px;transition:transform .35s cubic-bezier(.3,1.3,.5,1);max-width:calc(100% - 32px)}
.toast.show{transform:translate(-50%,0)}
.toast:not(.show),.sheet:not(.show),.savebar:not(.show){visibility:hidden;transition-property:transform,visibility;transition-delay:0s,.35s}
.toast i{width:9px;height:9px;border-radius:50%;background:var(--ok);flex:none}
.toast.err i{background:var(--bad)}
.spin{width:18px;height:18px;border-radius:50%;border:2.5px solid rgba(47,140,255,.25);border-top-color:var(--pri);animation:sp .8s linear infinite}
@keyframes sp{to{transform:rotate(360deg)}}
</style>
</head>
<body>
<svg width="0" height="0" style="position:absolute">
  <symbol id="i-power" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round"><path d="M12 3v8"/><path d="M6.3 7.2a8 8 0 1 0 11.4 0"/></symbol>
  <symbol id="i-home" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 11l9-7 9 7"/><path d="M5 10v10h14V10"/><path d="M10 20v-6h4v6"/></symbol>
  <symbol id="i-cal" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="5" width="18" height="16" rx="3"/><path d="M3 10h18M8 3v4M16 3v4"/><circle cx="12" cy="15.5" r="1.6" fill="currentColor" stroke="none"/></symbol>
  <symbol id="i-week" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M4 6h7M14 6h6M4 12h3M10 12h10M4 18h10M17 18h3"/></symbol>
  <symbol id="i-gear" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.8l.1.1a2 2 0 1 1-2.8 2.8l-.1-.1a1.7 1.7 0 0 0-1.8-.3 1.7 1.7 0 0 0-1 1.5V21a2 2 0 1 1-4 0v-.1a1.7 1.7 0 0 0-1.1-1.5 1.7 1.7 0 0 0-1.8.3l-.1.1a2 2 0 1 1-2.8-2.8l.1-.1a1.7 1.7 0 0 0 .3-1.8 1.7 1.7 0 0 0-1.5-1H3a2 2 0 1 1 0-4h.1a1.7 1.7 0 0 0 1.5-1.1 1.7 1.7 0 0 0-.3-1.8l-.1-.1a2 2 0 1 1 2.8-2.8l.1.1a1.7 1.7 0 0 0 1.8.3H9a1.7 1.7 0 0 0 1-1.5V3a2 2 0 1 1 4 0v.1a1.7 1.7 0 0 0 1 1.5 1.7 1.7 0 0 0 1.8-.3l.1-.1a2 2 0 1 1 2.8 2.8l-.1.1a1.7 1.7 0 0 0-.3 1.8V9a1.7 1.7 0 0 0 1.5 1H21a2 2 0 1 1 0 4h-.1a1.7 1.7 0 0 0-1.5 1z"/></symbol>
  <symbol id="i-plus" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round"><path d="M12 5v14M5 12h14"/></symbol>
  <symbol id="i-trash" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 7h16M10 11v6M14 11v6M6 7l1 13h10l1-13M9 7V4h6v3"/></symbol>
  <symbol id="i-copy" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="9" y="9" width="12" height="12" rx="3"/><path d="M5 15H4a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v1"/></symbol>
  <symbol id="i-arrow" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14M13 6l6 6-6 6"/></symbol>
  <symbol id="i-check" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3.2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12.5l4.5 4.5L19 7.5"/></symbol>
  <symbol id="i-clock" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></symbol>
  <symbol id="i-wifi" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round"><path d="M2 8.8a15 15 0 0 1 20 0M5 12.5a10 10 0 0 1 14 0M8.5 16a5 5 0 0 1 7 0"/><circle cx="12" cy="19.5" r="1.2" fill="currentColor"/></symbol>
  <symbol id="i-sun" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"><circle cx="12" cy="12" r="4.5"/><path d="M12 2v2M12 20v2M2 12h2M20 12h2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/></symbol>
</svg>

<div class="app">
  <header class="top">
    <div class="brand">
      <div class="logo"><svg><use href="#i-clock"/></svg></div>
      <div><h1>RelayTimer</h1><small id="sub">7-day smart switch</small></div>
    </div>
    <div class="clock"><b id="clk">--:--</b><span><i class="dot off" id="conn"></i><em id="clkday" style="font-style:normal">Connecting</em></span></div>
  </header>

  <div class="banner" id="timeBanner" hidden>
    <svg><use href="#i-clock"/></svg>
    <div class="grow"><b>Clock not set</b><span style="font-size:13px">Schedules start once the time is known.</span></div>
    <button class="btn sm" onclick="syncTime()">Sync</button>
  </div>

  <!-- HOME -->
  <section class="view on" id="v-home">
    <div id="relayCards"></div>
  </section>

  <!-- SCHEDULE -->
  <section class="view" id="v-sched">
    <div class="seg" id="segRelay"></div>
    <div class="days" id="days"></div>
    <div class="card" style="margin-top:12px">
      <div class="row">
        <div class="grow"><h3 style="margin:0;font-size:18px" id="dayTitle">Monday</h3><div class="tiny" id="daySum"></div></div>
        <button class="iconbtn" title="Copy to other days" onclick="openCopy()"><svg><use href="#i-copy"/></svg></button>
        <button class="iconbtn" title="Clear day" onclick="clearDay()"><svg><use href="#i-trash"/></svg></button>
      </div>
      <div class="tl" id="dayTl"></div>
      <div class="ticks"><span>00</span><span>06</span><span>12</span><span>18</span><span>24</span></div>
      <div id="slots"></div>
      <div class="toolbar">
        <button class="btn ghost" onclick="addSlot()"><svg><use href="#i-plus"/></svg>Add on/off period</button>
      </div>
    </div>
    <div class="tiny" style="text-align:center;margin-top:4px">An off time earlier than its on time runs overnight into the next day.</div>
  </section>

  <!-- WEEK -->
  <section class="view" id="v-week">
    <div id="weekCards"></div>
  </section>

  <!-- SETTINGS -->
  <section class="view" id="v-set">
    <div class="h2">Relays</div>
    <div class="card">
      <label class="fld" style="margin-top:0"><span>Relay 1 name</span><input class="inp" id="n0" maxlength="24"></label>
      <label class="fld"><span>Relay 2 name</span><input class="inp" id="n1" maxlength="24"></label>
      <button class="btn block" style="margin-top:14px" onclick="saveNames()">Save names</button>
    </div>

    <div class="h2">Time</div>
    <div class="card">
      <label class="fld" style="margin-top:0"><span>Time zone</span><select class="inp" id="tz"></select></label>
      <label class="fld" id="tzCustomWrap" hidden><span>POSIX TZ string</span><input class="inp" id="tzCustom" placeholder="e.g. CET-1CEST,M3.5.0,M10.5.0/3"></label>
      <div class="toolbar">
        <button class="btn ghost sm" onclick="detectTz()">Use phone's zone</button>
        <button class="btn ghost sm" onclick="syncTime()">Sync clock from phone</button>
      </div>
      <button class="btn block" style="margin-top:10px" onclick="saveTz()">Save time zone</button>
    </div>

    <div class="h2">Home Wi-Fi</div>
    <div class="card">
      <div class="row">
        <div class="iconbtn" style="background:var(--pri-soft);color:var(--pri)"><svg><use href="#i-wifi"/></svg></div>
        <div class="grow"><b id="staState">Not connected</b><div class="tiny" id="staInfo">Joining Wi-Fi gets internet time & a home address</div></div>
      </div>
      <label class="fld"><span>Network name</span>
        <div class="row"><input class="inp grow" id="ssid" autocomplete="off" autocapitalize="off"><button class="btn ghost sm" style="height:46px" onclick="scan()">Scan</button></div>
      </label>
      <label class="fld"><span>Password</span><input class="inp" id="pass" type="password" placeholder="unchanged"></label>
      <button class="btn block" style="margin-top:14px" onclick="saveWifi()">Connect</button>
    </div>

    <div class="h2">Timer hotspot</div>
    <div class="card">
      <div class="kv"><span>Hotspot</span><b id="apSsid">–</b></div>
      <div class="kv"><span>Address</span><b id="apIp">–</b></div>
      <label class="fld"><span>New hotspot password (8+ characters)</span><input class="inp" id="apPass" type="password"></label>
      <button class="btn ghost block" style="margin-top:14px" onclick="saveAp()">Change hotspot password</button>
    </div>

    <div class="h2">Device</div>
    <div class="card">
      <div class="kv"><span>Home address</span><b id="host">–</b></div>
      <div class="kv"><span>Uptime</span><b id="uptime">–</b></div>
      <div class="kv"><span>Device date</span><b id="ddate">–</b></div>
    </div>
  </section>
</div>

<div class="savebar" id="savebar">
  <div class="grow">Unsaved schedule changes</div>
  <button class="btn sm light" onclick="discard()">Discard</button>
  <button class="btn sm" onclick="saveSchedule()">Save</button>
</div>

<nav class="nav" id="nav">
  <button class="on" data-v="home"><svg><use href="#i-home"/></svg>Home</button>
  <button data-v="sched"><svg><use href="#i-cal"/></svg>Schedule</button>
  <button data-v="week"><svg><use href="#i-week"/></svg>Week</button>
  <button data-v="set"><svg><use href="#i-gear"/></svg>Settings</button>
</nav>

<div class="scrim" id="scrim" onclick="closeSheet()"></div>
<div class="sheet" id="sheet"><div class="grab"></div><div id="sheetBody"></div></div>
<div class="toast" id="toast"><i></i><span id="toastMsg"></span></div>

<script>
const DAYS = ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
const ORDER = [1,2,3,4,5,6,0];               // Monday-first display, data is 0 = Sunday
const TZS = [
  ['UTC','UTC0',['UTC','Etc/UTC']],
  ['US Eastern','EST5EDT,M3.2.0,M11.1.0',['America/New_York','America/Detroit','America/Toronto','America/Indiana/Indianapolis']],
  ['US Central','CST6CDT,M3.2.0,M11.1.0',['America/Chicago','America/Winnipeg']],
  ['US Mountain','MST7MDT,M3.2.0,M11.1.0',['America/Denver','America/Edmonton','America/Boise']],
  ['Arizona','MST7',['America/Phoenix']],
  ['US Pacific','PST8PDT,M3.2.0,M11.1.0',['America/Los_Angeles','America/Vancouver']],
  ['Alaska','AKST9AKDT,M3.2.0,M11.1.0',['America/Anchorage']],
  ['Hawaii','HST10',['Pacific/Honolulu']],
  ['Atlantic','AST4ADT,M3.2.0,M11.1.0',['America/Halifax']],
  ['Newfoundland','NST3:30NDT,M3.2.0,M11.1.0',['America/St_Johns']],
  ['Mexico City','CST6',['America/Mexico_City']],
  ['Brazil (São Paulo)','<-03>3',['America/Sao_Paulo']],
  ['UK / Ireland','GMT0BST,M3.5.0/1,M10.5.0',['Europe/London','Europe/Dublin']],
  ['Central Europe','CET-1CEST,M3.5.0,M10.5.0/3',['Europe/Paris','Europe/Berlin','Europe/Madrid','Europe/Rome','Europe/Amsterdam','Europe/Brussels','Europe/Vienna','Europe/Stockholm','Europe/Oslo','Europe/Copenhagen','Europe/Warsaw','Europe/Prague','Europe/Zurich']],
  ['Eastern Europe','EET-2EEST,M3.5.0/3,M10.5.0/4',['Europe/Athens','Europe/Helsinki','Europe/Kiev','Europe/Kyiv','Europe/Bucharest','Europe/Sofia']],
  ['South Africa','SAST-2',['Africa/Johannesburg']],
  ['Moscow','MSK-3',['Europe/Moscow']],
  ['Gulf (Dubai)','<+04>-4',['Asia/Dubai']],
  ['India','IST-5:30',['Asia/Kolkata','Asia/Calcutta']],
  ['China / Singapore','CST-8',['Asia/Shanghai','Asia/Singapore','Asia/Hong_Kong','Asia/Taipei','Asia/Manila']],
  ['Western Australia','AWST-8',['Australia/Perth']],
  ['Japan / Korea','JST-9',['Asia/Tokyo','Asia/Seoul']],
  ['Queensland','AEST-10',['Australia/Brisbane']],
  ['Sydney / Melbourne','AEST-10AEDT,M10.1.0,M4.1.0/3',['Australia/Sydney','Australia/Melbourne','Australia/Canberra','Australia/Hobart']],
  ['New Zealand','NZST-12NZDT,M9.5.0,M4.1.0/3',['Pacific/Auckland']],
];

const $ = id => document.getElementById(id);
let st = null, settings = null;
let sched = null, saved = null, maxSlots = 8;   // sched[relay][day] = [[on,off],...]
let curRelay = 0, curDay = new Date().getDay();
let syncedAt = 0, connected = false, timer = null;

// ----- helpers
const pad = n => String(n).padStart(2,'0');
const fmt = m => pad(Math.floor(m/60)) + ':' + pad(m%60);
const parse = s => { const [h,m] = s.split(':').map(Number); return h*60+m; };
const clone = o => JSON.parse(JSON.stringify(o));
const esc = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dirty = () => JSON.stringify(sched) !== JSON.stringify(saved);

async function api(path, body) {
  const r = await fetch(path, body === undefined ? {} : {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(body)});
  const j = await r.json().catch(() => ({}));
  if (!r.ok) throw new Error(j.error || ('HTTP ' + r.status));
  return j;
}
function toast(msg, err) {
  const t = $('toast'); $('toastMsg').textContent = msg;
  t.classList.toggle('err', !!err); t.classList.add('show');
  clearTimeout(t._h); t._h = setTimeout(() => t.classList.remove('show'), 2600);
}

// Mirror of the firmware rule: off < on means the period runs past midnight.
function onAt(r, d, m, s = sched) {
  for (const [a,b] of s[r][d]) { if (a < b ? (m >= a && m < b) : (a > b && m >= a)) return true; }
  for (const [a,b] of s[r][(d+6)%7]) { if (a > b && m < b) return true; }
  return false;
}
// Device local time right now, extrapolated from the last poll.
function devNow() {
  if (!st || !st.timeValid) return null;
  const secs = st.minute*60 + st.second + Math.floor((Date.now() - syncedAt)/1000);
  const extraDays = Math.floor(secs / 86400);
  const s = secs % 86400;
  return {wday:(st.wday + extraDays) % 7, minute:Math.floor(s/60), second:s%60};
}
function nextChange(r) {
  const n = devNow(); if (!n || !saved) return null;
  const cur = onAt(r, n.wday, n.minute, saved);
  for (let i = 1; i <= 7*1440; i++) {
    const t = n.minute + i, d = (n.wday + Math.floor(t/1440)) % 7, m = t % 1440;
    if (onAt(r, d, m, saved) !== cur) return {on:!cur, d, m, days:Math.floor(t/1440)};
  }
  return null;
}
function whenText(c) {
  return (c.days === 0 ? '' : c.days === 1 ? 'tomorrow ' : DAYS[c.d].slice(0,3) + ' ') + fmt(c.m);
}
// Pieces of the 24h bar for one day, including the tail of yesterday's overnight periods.
function segments(r, d, s = sched) {
  const out = [];
  for (const [a,b] of s[r][d]) { if (a < b) out.push([a,b]); else if (a > b) out.push([a,1440]); }
  for (const [a,b] of s[r][(d+6)%7]) if (a > b && b > 0) out.push([0,b]);
  return out;
}
function tlHtml(r, d, s, showNow) {
  let h = segments(r, d, s).map(([a,b]) => `<i style="left:${a/14.4}%;width:${(b-a)/14.4}%"></i>`).join('');
  const n = devNow();
  if (showNow && n && n.wday === d) h += `<span class="now" style="left:calc(${n.minute/14.4}% - 1px)"></span>`;
  return h;
}

// ----- segmented controls
function seg(el, items, active, onPick) {
  el.innerHTML = items.map((t,i) => `<button class="${i===active?'on':''}" data-i="${i}">${esc(t)}</button>`).join('') + '<span class="pill"></span>';
  const pill = el.querySelector('.pill');
  const place = i => { pill.style.width = `calc((100% - 8px)/${items.length})`; pill.style.transform = `translateX(${i*100}%)`; };
  place(active);
  el.onclick = e => {
    const b = e.target.closest('button'); if (!b) return;
    const i = +b.dataset.i;
    el.querySelectorAll('button').forEach((x,j) => x.classList.toggle('on', j===i));
    place(i); onPick(i);
  };
}

// ----- home
const MODES = ['auto','on','off'];
function renderHome() {
  if (!st) return;
  const box = $('relayCards');
  if (box.children.length !== st.relays.length) {
    box.innerHTML = st.relays.map((_,r) => `
      <div class="card relay" id="rc${r}">
        <div class="head">
          <div class="power"><svg><use href="#i-power"/></svg></div>
          <div class="grow"><h3></h3><div class="state"></div><div class="next"></div></div>
        </div>
        <div class="tl" data-tl></div>
        <div class="ticks"><span>00</span><span>06</span><span>12</span><span>18</span><span>24</span></div>
        <div class="seg"></div>
      </div>`).join('');
    st.relays.forEach((rl,r) => seg(box.querySelector(`#rc${r} .seg`), ['Auto','Always on','Always off'], MODES.indexOf(rl.mode), i => setMode(r, MODES[i])));
  }
  const n = devNow();
  st.relays.forEach((rl,r) => {
    const c = $('rc'+r);
    c.classList.toggle('is-on', rl.on);
    c.querySelector('h3').textContent = rl.name;
    c.querySelector('.state').textContent = rl.on ? '● ON' : '○ OFF';
    let txt;
    if (rl.mode === 'on') txt = 'Manual: held on';
    else if (rl.mode === 'off') txt = 'Manual: held off';
    else if (!st.timeValid) txt = 'Waiting for clock';
    else { const nc = nextChange(r); txt = nc ? `Turns ${nc.on ? 'on' : 'off'} ${whenText(nc)}` : 'No periods scheduled'; }
    c.querySelector('.next').textContent = txt;
    c.querySelector('[data-tl]').innerHTML = saved && n ? tlHtml(r, n.wday, saved, true) : '';
    const sg = c.querySelector('.seg'), mi = MODES.indexOf(rl.mode);
    if (!sg.querySelectorAll('button')[mi].classList.contains('on')) seg(sg, ['Auto','Always on','Always off'], mi, i => setMode(r, MODES[i]));
  });
}
async function setMode(r, mode) {
  try { st = await api('/api/relay', {relay:r, mode}); syncedAt = Date.now(); renderHome(); toast(`${st.relays[r].name}: ${mode === 'auto' ? 'following schedule' : 'held ' + mode}`); }
  catch (e) { toast(e.message, true); }
}

// ----- schedule editor
function renderSched() {
  if (!sched) return;
  const names = st ? st.relays.map(r => r.name) : ['Relay 1','Relay 2'];
  seg($('segRelay'), names, curRelay, i => { curRelay = i; renderSched(); });
  const n = devNow();
  $('days').innerHTML = ORDER.map(d => {
    const c = sched[curRelay][d].length;
    return `<button class="day ${d===curDay?'on':''} ${n&&n.wday===d?'today':''}" data-d="${d}">${DAYS[d].slice(0,3)}<small>${c ? c + '×' : '—'}</small></button>`;
  }).join('');
  $('days').onclick = e => { const b = e.target.closest('.day'); if (b) { curDay = +b.dataset.d; renderSched(); } };
  renderDay();
}
function renderDay() {
  const list = sched[curRelay][curDay];
  $('dayTitle').textContent = DAYS[curDay];
  const total = segments(curRelay, curDay).reduce((s,[a,b]) => s + b - a, 0);
  $('daySum').textContent = list.length ? `${list.length} period${list.length>1?'s':''} · on ${Math.floor(total/60)}h ${pad(total%60)}m` : 'Off all day';
  $('dayTl').innerHTML = tlHtml(curRelay, curDay, sched, true);
  $('slots').innerHTML = list.length ? list.map(([a,b],i) => {
    const dur = (b - a + 1440) % 1440;
    return `<div class="slot">
      <div class="f"><div class="lab">On</div><input type="time" value="${fmt(a)}" data-i="${i}" data-k="0"></div>
      <svg class="arrow" width="18" height="18"><use href="#i-arrow"/></svg>
      <div class="f"><div class="lab">Off</div><input type="time" value="${fmt(b)}" data-i="${i}" data-k="1"></div>
      <button class="iconbtn" data-del="${i}" title="Remove"><svg><use href="#i-trash"/></svg></button>
    </div><div class="tiny" style="margin:4px 0 0 14px">${dur ? `${Math.floor(dur/60)}h ${pad(dur%60)}m${a > b ? ' · overnight' : ''}` : '<span style="color:var(--bad)">On and off are the same — ignored</span>'}</div>`;
  }).join('') : `<div class="empty"><svg><use href="#i-sun"/></svg><div style="margin-top:6px;font-weight:600">Nothing scheduled</div><div class="tiny">Add a period to switch ${esc(st ? st.relays[curRelay].name : 'this relay')} on.</div></div>`;
  $('slots').querySelectorAll('input[type=time]').forEach(inp => inp.onchange = () => {
    if (!inp.value) return;
    list[+inp.dataset.i][+inp.dataset.k] = parse(inp.value);
    list.sort((x,y) => x[0]-y[0]); changed(); renderSched();
  });
  $('slots').querySelectorAll('[data-del]').forEach(b => b.onclick = () => { list.splice(+b.dataset.del,1); changed(); renderSched(); });
}
function addSlot() {
  const list = sched[curRelay][curDay];
  if (list.length >= maxSlots) return toast(`Up to ${maxSlots} periods per day`, true);
  const last = list.length ? list[list.length-1][1] : 7*60;
  const on = Math.min(last + 60, 22*60), off = Math.min(on + 60, 23*60 + 59);
  list.push([on, off]); list.sort((x,y) => x[0]-y[0]); changed(); renderSched();
}
function clearDay() {
  if (!sched[curRelay][curDay].length) return;
  sched[curRelay][curDay] = []; changed(); renderSched(); toast(`${DAYS[curDay]} cleared`);
}
function changed() { const d = dirty(); $('savebar').classList.toggle('show', d); document.body.classList.toggle('dirty', d); }
function discard() { sched = clone(saved); changed(); renderSched(); }
async function saveSchedule() {
  try {
    const j = await api('/api/schedule', {relays:sched});
    saved = j.relays; sched = clone(saved); changed(); renderSched(); renderWeek(); renderHome();
    toast('Schedule saved to timer');
  } catch (e) { toast(e.message, true); }
}

// ----- copy sheet
function openSheet(html) { $('sheetBody').innerHTML = html; $('scrim').classList.add('show'); $('sheet').classList.add('show'); }
function closeSheet() { $('scrim').classList.remove('show'); $('sheet').classList.remove('show'); }
const chk = (id, label, checked, disabled) => `<label class="chk"><input type="checkbox" id="${id}" ${checked?'checked':''} ${disabled?'disabled':''}><span class="box"><svg><use href="#i-check"/></svg></span><span class="grow">${label}</span></label>`;
function openCopy() {
  const other = st ? st.relays[1-curRelay].name : 'other relay';
  openSheet(`<h3>Copy ${DAYS[curDay]}</h3><div class="tiny" style="margin-bottom:6px">Replace the periods on the selected days with this day's.</div>
    <div class="toolbar" style="margin:8px 0 2px">
      <button class="btn ghost sm" onclick="pickDays([1,2,3,4,5])">Weekdays</button>
      <button class="btn ghost sm" onclick="pickDays([0,6])">Weekend</button>
      <button class="btn ghost sm" onclick="pickDays([0,1,2,3,4,5,6])">All</button>
    </div>
    ${ORDER.map(d => chk('cp'+d, DAYS[d], false)).join('')}
    <div class="h2" style="margin-top:16px">Also</div>
    ${chk('cpOther', `Apply to ${esc(other)} too`, false)}
    <button class="btn block" style="margin-top:16px" onclick="doCopy()">Copy</button>`);
  $('cp'+curDay).checked = true;
}
function pickDays(ds) { ORDER.forEach(d => $('cp'+d).checked = ds.includes(d) || d === curDay); }
function doCopy() {
  const src = clone(sched[curRelay][curDay]);
  const relays = $('cpOther').checked ? [0,1] : [curRelay];
  let n = 0;
  for (const r of relays) for (const d of ORDER) if ($('cp'+d).checked && !(r === curRelay && d === curDay)) { sched[r][d] = clone(src); n++; }
  closeSheet(); changed(); renderSched();
  toast(n ? `Copied to ${n} day${n>1?'s':''} — remember to save` : 'Nothing selected');
}

// ----- week overview
function renderWeek() {
  if (!saved) return;
  const n = devNow(), names = st ? st.relays.map(r => r.name) : ['Relay 1','Relay 2'];
  $('weekCards').innerHTML = names.map((nm,r) => `
    <div class="card">
      <div class="row" style="margin-bottom:12px"><div class="grow"><h3 style="margin:0;font-size:17px">${esc(nm)}</h3>
        <div class="tiny">${(() => { const t = ORDER.reduce((s,d) => s + segments(r,d,saved).reduce((x,[a,b]) => x+b-a,0),0); return `On ${Math.floor(t/60)}h ${pad(t%60)}m per week`; })()}</div></div></div>
      <div class="wk">${ORDER.map(d => `<b class="${n&&n.wday===d?'today':''}">${DAYS[d].slice(0,3)}</b><div class="tl slim" data-r="${r}" data-d="${d}">${tlHtml(r,d,saved,true)}</div>`).join('')}</div>
      <div class="wk" style="margin-top:4px"><span></span><div class="ticks" style="margin:0"><span>00</span><span>06</span><span>12</span><span>18</span><span>24</span></div></div>
    </div>`).join('') + '<div class="tiny" style="text-align:center">Tap a day to edit it.</div>';
  $('weekCards').querySelectorAll('.tl[data-d]').forEach(el => el.onclick = () => { curRelay = +el.dataset.r; curDay = +el.dataset.d; go('sched'); });
}

// ----- settings
function fillTzSelect(cur) {
  const known = TZS.some(t => t[1] === cur);
  $('tz').innerHTML = TZS.map(t => `<option value="${esc(t[1])}">${esc(t[0])}</option>`).join('') + '<option value="custom">Custom…</option>';
  $('tz').value = known ? cur : 'custom';
  $('tzCustom').value = cur;
  $('tzCustomWrap').hidden = known;
}
$('tz').onchange = () => { $('tzCustomWrap').hidden = $('tz').value !== 'custom'; };
function renderSettings() {
  if (!settings) return;
  $('n0').value = settings.names[0]; $('n1').value = settings.names[1];
  if (document.activeElement !== $('ssid')) $('ssid').value = settings.ssid;
  $('pass').placeholder = settings.hasPass ? 'unchanged' : 'none';
  $('staState').textContent = settings.staConnected ? `Connected to ${settings.ssid}` : settings.ssid ? `Connecting to ${settings.ssid}…` : 'Not connected';
  $('staInfo').textContent = settings.staConnected ? `IP ${settings.staIp} · signal ${settings.rssi} dBm` : 'Joining Wi-Fi gets internet time & a home address';
  $('apSsid').textContent = settings.apSsid; $('apIp').textContent = 'http://' + settings.apIp;
  $('host').textContent = settings.staConnected ? `http://${settings.host}` : '(join home Wi-Fi first)';
}
async function loadSettings() {
  try { settings = await api('/api/settings'); fillTzSelect(settings.tz); renderSettings(); } catch (e) {}
}
async function postSettings(body, msg) {
  try { settings = await api('/api/settings', body); renderSettings(); toast(msg); await poll(); }
  catch (e) { toast(e.message, true); }
}
function saveNames() { postSettings({names:[$('n0').value, $('n1').value]}, 'Names saved').then(() => { $('relayCards').innerHTML = ''; renderAll(); }); }
function saveTz() {
  const v = $('tz').value === 'custom' ? $('tzCustom').value.trim() : $('tz').value;
  if (!v) return toast('Enter a TZ string', true);
  postSettings({tz:v}, 'Time zone saved');
}
function detectTz() {
  const z = Intl.DateTimeFormat().resolvedOptions().timeZone;
  const hit = TZS.find(t => t[2].includes(z));
  if (hit) { $('tz').value = hit[1]; $('tzCustomWrap').hidden = true; toast(`Selected ${hit[0]} — tap Save`); }
  else toast(`No preset for ${z}; use Custom`, true);
}
function saveWifi() {
  const ssid = $('ssid').value.trim(), pass = $('pass').value;
  const body = {ssid}; if (pass || !ssid) body.pass = pass;
  postSettings(body, ssid ? `Connecting to ${ssid}…` : 'Home Wi-Fi removed');
  $('pass').value = '';
  setTimeout(loadSettings, 6000);
}
function saveAp() {
  const p = $('apPass').value;
  if (p.length < 8) return toast('Use at least 8 characters', true);
  postSettings({apPass:p}, 'Hotspot password changed — rejoin with the new one');
  $('apPass').value = '';
}
async function scan() {
  openSheet('<h3>Nearby networks</h3><div class="row" style="padding:24px 0;justify-content:center"><div class="spin"></div><span class="muted">Scanning…</span></div>');
  try {
    const j = await api('/api/scan');
    const nets = [...new Map(j.networks.filter(n => n.ssid).sort((a,b) => b.rssi-a.rssi).map(n => [n.ssid,n])).values()];
    $('sheetBody').innerHTML = '<h3>Nearby networks</h3>' + (nets.length ? nets.map(n => {
      const q = n.rssi > -55 ? 4 : n.rssi > -67 ? 3 : n.rssi > -78 ? 2 : 1;
      return `<button class="net" data-s="${esc(n.ssid)}"><span class="bars">${[6,9,12,16].map((h,i) => `<i class="${i<q?'f':''}" style="height:${h}px"></i>`).join('')}</span><span class="grow"><b>${esc(n.ssid)}</b></span><span class="tiny">${n.secure ? '🔒' : 'open'}</span></button>`;
    }).join('') : '<div class="empty">No networks found</div>');
    $('sheetBody').querySelectorAll('.net').forEach(b => b.onclick = () => { $('ssid').value = b.dataset.s; closeSheet(); $('pass').focus(); });
  } catch (e) { closeSheet(); toast(e.message, true); }
}
async function syncTime() {
  try { st = await api('/api/time', {epoch:Math.floor(Date.now()/1000)}); syncedAt = Date.now(); renderAll(); toast('Clock synced from your phone'); }
  catch (e) { toast(e.message, true); }
}

// ----- navigation / polling
function go(v) {
  document.querySelectorAll('.view').forEach(x => x.classList.toggle('on', x.id === 'v-'+v));
  document.querySelectorAll('#nav button').forEach(b => b.classList.toggle('on', b.dataset.v === v));
  if (v === 'sched') renderSched();
  if (v === 'week') renderWeek();
  if (v === 'set') loadSettings();
  window.scrollTo({top:0, behavior:'smooth'});
}
$('nav').onclick = e => { const b = e.target.closest('button'); if (b) go(b.dataset.v); };

function tick() {
  const n = devNow();
  $('conn').classList.toggle('off', !connected);
  if (n) { $('clk').textContent = fmt(n.minute) + ':' + pad(n.second); $('clkday').textContent = DAYS[n.wday]; }
  else { $('clk').textContent = '--:--'; $('clkday').textContent = connected ? 'Clock not set' : 'Offline'; }
  $('timeBanner').hidden = !st || st.timeValid;
  if (n && n.second === 0) renderAll();
}
function renderAll() {
  renderHome();
  if ($('v-week').classList.contains('on')) renderWeek();
  if ($('v-sched').classList.contains('on')) $('dayTl').innerHTML = tlHtml(curRelay, curDay, sched, true);
  if (st) {
    const u = st.uptime, d = Math.floor(u/86400), h = Math.floor(u%86400/3600), m = Math.floor(u%3600/60);
    $('uptime').textContent = (d ? d + 'd ' : '') + h + 'h ' + m + 'm';
    $('ddate').textContent = st.date || 'not set';
  }
}
let autoSynced = false;
async function poll() {
  try {
    st = await api('/api/state'); syncedAt = Date.now(); connected = true;
    if (!st.timeValid && !autoSynced) { autoSynced = true; await syncTime(); }
  } catch (e) { connected = false; }
  renderAll(); tick();
}
async function init() {
  await poll();
  try {
    const j = await api('/api/schedule');
    maxSlots = j.maxSlots; saved = j.relays; sched = clone(saved);
    if (st && st.timeValid) curDay = st.wday;
  } catch (e) { toast('Could not reach the timer', true); }
  renderAll();
  loadSettings();
  setInterval(poll, 5000);
  setInterval(tick, 1000);
}
window.addEventListener('beforeunload', e => { if (sched && dirty()) { e.preventDefault(); e.returnValue = ''; } });
init();
</script>
</body>
</html>
)rawliteral";
