#!/usr/bin/env python3
"""Embed web/index.html into the sketch as RelayTimer/index_html.h.

Run after editing the web app:  python3 tools/embed_html.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "web" / "index.html"
DST = ROOT / "RelayTimer" / "index_html.h"
DELIM = "rawliteral"


def main():
    html = SRC.read_text(encoding="utf-8")
    if f'){DELIM}"' in html:
        raise SystemExit(f"index.html contains the raw-string terminator ){DELIM}\"")
    DST.write_text(
        "// Generated by tools/embed_html.py from web/index.html - do not edit.\n"
        "#pragma once\n"
        "#include <pgmspace.h>\n\n"
        f'static const char INDEX_HTML[] PROGMEM = R"{DELIM}({html}){DELIM}";\n',
        encoding="utf-8",
    )
    print(f"wrote {DST.relative_to(ROOT)} ({len(html.encode())} bytes of HTML)")


if __name__ == "__main__":
    main()
